#!/usr/bin/env node

/**
 * Ghost -> Astro content migration.
 *
 * This module exposes small pure functions (mapping, tag joins, body cleanup,
 * image rewriting, redirect generation) so the migration is unit-testable, plus
 * a `main()` that performs the file I/O. `main()` only runs when the script is
 * executed directly (`node scripts/migrate-ghost.js`), not when imported by tests.
 *
 * Source of truth: specs/refs/brian-erickson.ghost.2026-06-05.json (sanitized).
 * Idempotent: existing markdown is never overwritten unless `--force` is passed.
 */

import {
  copyFileSync,
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  writeFileSync,
} from "node:fs";
import { basename, dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

export const BME_FORMAT_LINK_SLUG = "bme_format_link";

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), "..");

const PATHS = {
  ghostExport: join(repoRoot, "specs/refs/brian-erickson.ghost.2026-06-05.json"),
  imageSourceDirs: [
    join(repoRoot, "specs/refs/original-site/ghost-images"),
    join(repoRoot, "specs/refs/original-site/legacy/images"),
  ],
  blogDir: join(repoRoot, "src/content/blog"),
  aboutFile: join(repoRoot, "src/data/about.md"),
  imageOutDir: join(repoRoot, "public/images/blog"),
  redirectsFile: join(repoRoot, "public/_redirects"),
  linkAudit: join(repoRoot, "specs/refs/link-audit.json"),
};

const NEW_IMAGE_BASE = "/images/blog";
const MANUAL_REDIRECTS_MARKER = "# Manual redirects";
const GENERATED_REDIRECTS_HEADER = [
  "# Generated by scripts/migrate-ghost.js — do not edit this section by hand.",
  "# Re-run `npm run migrate:ghost -- --force` to regenerate.",
].join("\n");

// ---------------------------------------------------------------------------
// Pure data helpers
// ---------------------------------------------------------------------------

/** Returns the `data` object from a parsed Ghost export. */
export function getExportData(exportJson) {
  return exportJson.db[0].data;
}

/** Published, non-page posts (the 19 real blog posts). */
export function getPublishedPosts(data) {
  return data.posts
    .filter((post) => post.status === "published" && post.page === 0)
    .sort((a, b) => a.published_at - b.published_at);
}

/** The single published `page: 1` entry (About Me), or undefined. */
export function getAboutPage(data) {
  return data.posts.find((post) => post.page === 1 && post.status === "published");
}

/**
 * Resolves the tag names for a post via the posts_tags join table, ordered by
 * sort_order, with the internal `bme_format_link` tag removed.
 */
export function joinTags(post, data) {
  const tagsById = new Map(data.tags.map((tag) => [tag.id, tag]));
  return data.posts_tags
    .filter((row) => row.post_id === post.id)
    .sort((a, b) => a.sort_order - b.sort_order)
    .map((row) => tagsById.get(row.tag_id))
    .filter((tag) => tag && tag.slug !== BME_FORMAT_LINK_SLUG)
    .map((tag) => tag.name);
}

/** Converts a Ghost timestamp (unix ms) to a YYYY-MM-DD UTC date string. */
export function unixMsToDate(ms) {
  return new Date(ms).toISOString().slice(0, 10);
}

/** True when a meta_description reads like prose rather than a bare URL/blank. */
export function isProseDescription(value) {
  if (!value) return false;
  const trimmed = value.trim();
  if (trimmed.length === 0) return false;
  // A single bare URL (no spaces) is not prose.
  if (/^https?:\/\/\S+$/i.test(trimmed)) return false;
  return true;
}

/** Strips markdown syntax down to readable plain text (for excerpts). */
export function stripMarkdown(markdown) {
  return markdown
    .replace(/<!--more-->/g, " ")
    .replace(/```[\s\S]*?```/g, " ") // fenced code
    .replace(/!\[[^\]]*\]\([^)]*\)/g, " ") // images
    .replace(/\[([^\]]*)\]\([^)]*\)/g, "$1") // links -> text
    .replace(/^>\s?/gm, "") // blockquote markers
    .replace(/^#{1,6}\s+/gm, "") // headings
    .replace(/[*_`#]/g, "") // residual emphasis/code marks
    .replace(/\s+/g, " ")
    .trim();
}

/** Builds a ~150-160 char description from a markdown body at a word boundary. */
export function deriveDescriptionFromBody(markdown, maxLength = 160) {
  const text = stripMarkdown(markdown);
  if (text.length <= maxLength) return text;
  const slice = text.slice(0, maxLength);
  const lastSpace = slice.lastIndexOf(" ");
  // Prefer a word boundary, but only if it keeps most of the budget.
  const truncated = lastSpace > maxLength * 0.6 ? slice.slice(0, lastSpace) : slice;
  return `${truncated.replace(/[\s.,;:!?-]+$/, "")}…`;
}

/** Final description for a post: prose meta_description, else derived from body. */
export function resolveDescription(post) {
  if (isProseDescription(post.meta_description)) {
    return post.meta_description.trim();
  }
  return deriveDescriptionFromBody(post.markdown || "");
}

/** Rewrites a legacy Ghost image path to the clean /images/blog/<file> path. */
export function rewriteImagePath(src) {
  if (/^https?:\/\//i.test(src)) return src; // leave remote images alone
  return `${NEW_IMAGE_BASE}/${basename(src)}`;
}

/** Removes utm_* (and similar tracking) params from a URL, preserving the rest. */
export function stripTrackingParams(url) {
  const hashIndex = url.indexOf("#");
  const hash = hashIndex >= 0 ? url.slice(hashIndex) : "";
  const noHash = hashIndex >= 0 ? url.slice(0, hashIndex) : url;
  const queryIndex = noHash.indexOf("?");
  if (queryIndex < 0) return url;
  const base = noHash.slice(0, queryIndex);
  const params = noHash
    .slice(queryIndex + 1)
    .split("&")
    .filter((pair) => pair && !/^utm_/i.test(pair));
  return params.length > 0 ? `${base}?${params.join("&")}${hash}` : `${base}${hash}`;
}

/** All local image paths referenced by a markdown body. */
export function extractImageRefs(markdown) {
  const refs = [];
  const re = /!\[[^\]]*\]\(([^)]+)\)/g;
  let match;
  while ((match = re.exec(markdown))) {
    if (!/^https?:\/\//i.test(match[1])) refs.push(match[1]);
  }
  return refs;
}

/** All external (http/https) URLs referenced by a markdown body. */
export function extractExternalLinks(markdown) {
  const links = new Set();
  const re = /\]\((https?:\/\/[^)]+)\)/g;
  let match;
  while ((match = re.exec(markdown))) {
    links.add(match[1]);
  }
  return [...links];
}

/**
 * Cleans a Ghost markdown body for the new site:
 * - drops the `<!--more-->` excerpt marker
 * - rewrites local image paths to /images/blog/<file>
 * - strips utm_* tracking params from links
 */
export function cleanBody(markdown) {
  let body = markdown.replace(/<!--more-->\s*/g, "");

  // Rewrite image targets.
  body = body.replace(/(!\[[^\]]*\]\()([^)]+)(\))/g, (_full, open, src, close) => {
    return `${open}${rewriteImagePath(src.trim())}${close}`;
  });

  // Strip tracking params from non-image links only.
  body = body.replace(/(?<!!)(\[[^\]]*\]\()([^)]+)(\))/g, (_full, open, href, close) => {
    return `${open}${stripTrackingParams(href.trim())}${close}`;
  });

  return body.trim();
}

/** Serializes a frontmatter object to YAML (handles the fields we emit). */
export function toFrontmatter(fields) {
  const lines = ["---"];
  for (const [key, value] of Object.entries(fields)) {
    if (value === undefined) continue;
    if (Array.isArray(value)) {
      if (value.length === 0) {
        lines.push(`${key}: []`);
      } else {
        lines.push(`${key}:`);
        for (const item of value) lines.push(`  - ${yamlScalar(item)}`);
      }
    } else if (typeof value === "boolean" || typeof value === "number") {
      lines.push(`${key}: ${value}`);
    } else {
      lines.push(`${key}: ${yamlScalar(value)}`);
    }
  }
  lines.push("---");
  return lines.join("\n");
}

function yamlScalar(value) {
  if (typeof value === "number" || typeof value === "boolean") return String(value);
  const str = String(value);
  // Quote strings that could be misread by YAML or contain risky characters.
  if (str === "" || /[:#\-?*&!|>'"%@`{}[\],]/.test(str) || /^\s|\s$/.test(str)) {
    return `"${str.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
  }
  return str;
}

/** Builds the full markdown file (frontmatter + body) for a published post. */
export function buildPostFile(post, data) {
  const frontmatter = toFrontmatter({
    title: post.title,
    date: unixMsToDate(post.published_at),
    tags: joinTags(post, data),
    description: resolveDescription(post),
    draft: false,
    ghost_id: post.id,
  });
  const body = cleanBody(post.markdown || "");
  return {
    slug: post.slug,
    filename: `${post.slug}.md`,
    contents: `${frontmatter}\n\n${body}\n`,
  };
}

/**
 * Builds the generated redirect lines for migrated posts:
 * - /slug and /slug/ -> /blog/slug/
 * - legacy image paths -> /images/blog/<file>
 */
export function buildGeneratedRedirects(posts) {
  const lines = [];
  for (const post of posts) {
    lines.push(`/${post.slug} /blog/${post.slug}/ 301`);
    lines.push(`/${post.slug}/ /blog/${post.slug}/ 301`);
  }

  const imagePaths = new Set();
  for (const post of posts) {
    for (const ref of extractImageRefs(post.markdown || "")) {
      imagePaths.add(ref);
    }
  }
  for (const src of [...imagePaths].sort()) {
    lines.push(`${src} ${rewriteImagePath(src)} 301`);
  }

  return lines;
}

/**
 * Composes the full _redirects file, preserving any existing manual section.
 * The generated section is always rebuilt; everything from the
 * "# Manual redirects" marker onward is preserved verbatim (or seeded with the
 * default /about -> /resume rules when no manual section exists yet).
 */
export function composeRedirects(generatedLines, existingContent) {
  const manual = extractManualSection(existingContent);
  return [
    GENERATED_REDIRECTS_HEADER,
    "",
    ...generatedLines,
    "",
    manual,
    "",
  ].join("\n");
}

function extractManualSection(existingContent) {
  if (existingContent) {
    const index = existingContent.indexOf(MANUAL_REDIRECTS_MARKER);
    if (index >= 0) {
      return existingContent.slice(index).trim();
    }
  }
  return [MANUAL_REDIRECTS_MARKER, "/about /resume/ 301", "/about/ /resume/ 301"].join("\n");
}

/** Write decision: never overwrite an existing target unless `--force`. */
export function shouldWrite(targetExists, force) {
  return !targetExists || force;
}

// ---------------------------------------------------------------------------
// File I/O orchestration
// ---------------------------------------------------------------------------

function buildImageSourceIndex() {
  const index = new Map();
  for (const dir of PATHS.imageSourceDirs) {
    if (!existsSync(dir)) continue;
    for (const file of readdirSync(dir)) {
      if (!index.has(file)) index.set(file, join(dir, file));
    }
  }
  return index;
}

function ensureDir(dir) {
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
}

function main() {
  const force = process.argv.includes("--force");

  if (!existsSync(PATHS.ghostExport)) {
    throw new Error(`Ghost export not found: ${PATHS.ghostExport}`);
  }

  const data = getExportData(JSON.parse(readFileSync(PATHS.ghostExport, "utf8")));
  const posts = getPublishedPosts(data);
  const imageIndex = buildImageSourceIndex();

  ensureDir(PATHS.blogDir);
  ensureDir(PATHS.imageOutDir);
  ensureDir(dirname(PATHS.aboutFile));

  const summary = {
    written: [],
    skipped: [],
    imagesCopied: [],
    imagesMissing: [],
  };

  // 1. Blog posts.
  for (const post of posts) {
    const file = buildPostFile(post, data);
    const target = join(PATHS.blogDir, file.filename);
    if (!shouldWrite(existsSync(target), force)) {
      summary.skipped.push(file.filename);
      continue;
    }
    writeFileSync(target, file.contents);
    summary.written.push(file.filename);
  }

  // 2. Images referenced by post bodies.
  const referencedImages = new Set();
  for (const post of posts) {
    for (const ref of extractImageRefs(post.markdown || "")) {
      referencedImages.add(basename(ref));
    }
  }
  for (const name of [...referencedImages].sort()) {
    const target = join(PATHS.imageOutDir, name);
    const source = imageIndex.get(name);
    if (!source) {
      summary.imagesMissing.push(name);
      continue;
    }
    if (!shouldWrite(existsSync(target), force)) continue;
    copyFileSync(source, target);
    summary.imagesCopied.push(name);
  }

  // 3. About page reference content.
  const about = getAboutPage(data);
  if (about && shouldWrite(existsSync(PATHS.aboutFile), force)) {
    const aboutBody = cleanBody(about.markdown || "");
    const aboutDoc = `${toFrontmatter({
      title: about.title || "About",
      source: "Ghost export (stale; historical reference only)",
      ghost_id: about.id,
    })}\n\n${aboutBody}\n`;
    writeFileSync(PATHS.aboutFile, aboutDoc);
    summary.aboutWritten = true;
  }

  // 4. Redirects (always regenerated; manual section preserved).
  const existingRedirects = existsSync(PATHS.redirectsFile)
    ? readFileSync(PATHS.redirectsFile, "utf8")
    : "";
  const redirects = composeRedirects(buildGeneratedRedirects(posts), existingRedirects);
  writeFileSync(PATHS.redirectsFile, redirects);

  // 5. External link audit (no network checks).
  const auditEntries = posts.map((post) => ({
    slug: post.slug,
    links: extractExternalLinks(post.markdown || ""),
  }));
  writeFileSync(PATHS.linkAudit, `${JSON.stringify({ generatedFrom: "published posts", posts: auditEntries }, null, 2)}\n`);

  // Report.
  console.log(`Ghost migration complete (${force ? "force" : "idempotent"} mode).`);
  console.log(`  Posts written:  ${summary.written.length}`);
  console.log(`  Posts skipped:  ${summary.skipped.length}${summary.skipped.length ? ` (${summary.skipped.join(", ")})` : ""}`);
  console.log(`  Images copied:  ${summary.imagesCopied.length}`);
  if (summary.imagesMissing.length) {
    console.warn(`  Images MISSING: ${summary.imagesMissing.join(", ")}`);
  }
  console.log(`  About page:     ${summary.aboutWritten ? "written" : "skipped (exists)"}`);
  console.log(`  Redirects:      ${PATHS.redirectsFile}`);
  console.log(`  Link audit:     ${PATHS.linkAudit}`);
}

const invokedDirectly = process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1];
if (invokedDirectly) {
  main();
}
